### PR TITLE
fix: resend invitation

### LINKED ISSUE #5901: 🐛 Bug Report: When trying to resend email in Organization tab it throws AppwriteException
### 👟 Reproduction steps

Try to hit resend on an unclaimed email invite

### 👍 Expected behavior

resend the email

### 👎 Actual Behavior

Appwrite Exception 
image

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.3.8, Cloudflare, Appwrite is self hosted as a reverse proxy using Nginx

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by ChiragAgg5k**
## What does this PR do?

Fixes #5901

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Screenshots may also be helpful.)

## Related PRs and Issues

- #8531

## Checklist

- [ ] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

File: app/controllers/api/teams.php [hunk 1]
```diff
@@ -546,45 +546,57 @@
...
+                'teamInternalId' => $team->getInternalId(),
+                'roles' => $roles,
+                'invited' => DateTime::now(),
+                'joined' => ($isPrivilegedUser || $isAppUser) ? DateTime::now() : null,
+                'confirm' => ($isPrivilegedUser || $isAppUser),
+                'secret' => Auth::hash($secret),
+                'search' => implode(' ', [$membershipId, $invitee->getId()])
+            ]);
+
+            $createdMembership = true;
```
Comment (loks0n) [inline app/controllers/api/teams.php:580]: is it possible to avoid this `createdMembership` var? and just group the side effects together?

Comment (loks0n) [reply app/controllers/api/teams.php:580]: something like:
```
$membership = findOne(...)
if ($membership->isEmpty()) {
    $membership = new Document (...)
    $dbForProject->createDocument($membership)
    Authorization::skip(fn () => $dbForProject->increaseDocumentAttribute('teams', $team->getId(), 'total', 1));
 else {
    $dbForProject->updateDocument('memberships', $membership->getId(), $membership);
 }
 ```

**Review by loks0n — APPROVED** [review]

File: app/controllers/api/teams.php (hunk 1 above)
Comment (ChiragAgg5k) [reply app/controllers/api/teams.php]: done!

File: tests/e2e/Services/Teams/TeamsBaseClient.php [hunk 2]
```diff
@@ -292,9 +292,9 @@ public function testCreateTeamMembership($data): array
         $this->assertEquals('Invitation to ' . $teamName . ' Team at ' . $this->getProject()['name'], $lastEmail['subject']);
 
         /**
-         * Test for FAILURE
+         * Test for resend
+         * SUCCESS
          */
-
```
Comment (stnguyen90) [inline tests/e2e/Services/Teams/TeamsBaseClient.php:297]: No need to make a test for resend success block here. you can just add a 1 line comment saying this tests resending the invite.

File: app/controllers/api/teams.php [hunk 3]
```diff
@@ -546,47 +546,51 @@
...
-            'teamInternalId' => $team->getInternalId(),
-            'roles' => $roles,
-            'invited' => DateTime::now(),
-            'joined' => ($isPrivilegedUser || $isAppUser) ? DateTime::now() : null,
-            'confirm' => ($isPrivilegedUser || $isAppUser),
-            'secret' => Auth::hash($secret),
-            'search' => implode(' ', [$membershipId, $invitee->getId()])
+        $membership = $dbForProject->findOne('memberships', [
+            Query::equal('userId', [$invitee->getId()]),
+            Query::equal('teamId', [$team->getId()]),
```
Comment (stnguyen90) [inline app/controllers/api/teams.php:551]: We should always be using the internal iDs instead of the public IDs.

File: app/controllers/api/teams.php [hunk 4]
```diff
@@ -546,47 +546,51 @@
...
-            $dbForProject->purgeCachedDocument('users', $invitee->getId());
         } else {
-            try {
-                $membership = $dbForProject->createDocument('memberships', $membership);
-            } catch (Duplicate $th) {
-                throw new Exception(Exception::TEAM_INVITE_ALREADY_EXISTS);
-            }
+            $membership = ($isPrivilegedUser || $isAppUser) ?
+                Authorization::skip(fn () => $dbForProject->updateDocument('memberships', $membership->getId(), $membership)) :
+                $dbForProject->updateDocument('memberships', $membership->getId(), $membership);
```
Comment (stnguyen90) [inline app/controllers/api/teams.php:587]: What would this be updating?

File: app/controllers/api/teams.php [hunk 5]
```diff
@@ -546,47 +546,51 @@
...
+        }
+
 
+        if ($isPrivilegedUser || $isAppUser) {
+            $dbForProject->purgeCachedDocument('users', $invitee->getId());
```
Comment (stnguyen90) [inline app/controllers/api/teams.php:592]: Why would this be needed?

**Review by stnguyen90 — COMMENTED** [review]
Want to fix https://github.com/appwrite/appwrite/issues/8825 too since you're modifying the same area of code?

File: app/controllers/api/teams.php (hunk 4 above)
Comment (ChiragAgg5k) [reply app/controllers/api/teams.php:587]: I guess it updates the `invited` field with the current timestamp. maybe i can switch it to just update that field instead of the entire document

File: app/controllers/api/teams.php (hunk 3 above)
Comment (ChiragAgg5k) [reply app/controllers/api/teams.php:551]: got itt

File: app/controllers/api/teams.php (hunk 5 above)
Comment (ChiragAgg5k) [reply app/controllers/api/teams.php:592]: @stnguyen90  It was present in the previous code... and i guess its there because we don't send verification email if the user is privileged? not entirely sure as well

File: app/controllers/api/teams.php (hunk 4 above)
Comment (stnguyen90) [reply app/controllers/api/teams.php:587]: Where is the invited timestamp being updated?

Also, this should probably update joined and confirmed for privileged and app users.

Comment (ChiragAgg5k) [reply app/controllers/api/teams.php:587]: @stnguyen90 it does so here -
https://github.com/ChiragAgg5k/appwrite/blob/8dc3b4ca6032c337e7f0e9a0f6b078d90a38e83f/app/controllers/api/teams.php#L573-L574

Comment (ChiragAgg5k) [reply app/controllers/api/teams.php:587]: ohh right, ig i skipped it, fixing

File: app/controllers/api/teams.php [hunk 6]
```diff
@@ -546,47 +546,57 @@
...
             Authorization::skip(fn () => $dbForProject->increaseDocumentAttribute('teams', $team->getId(), 'total', 1));
 
-            $dbForProject->purgeCachedDocument('users', $invitee->getId());
         } else {
-            try {
-                $membership = $dbForProject->createDocument('memberships', $membership);
-            } catch (Duplicate $th) {
-                throw new Exception(Exception::TEAM_INVITE_ALREADY_EXISTS);
-            }
+            $membership = new Document([
```
Comment (stnguyen90) [inline app/controllers/api/teams.php:585]: What happens to the rest of the attributes if you initialize a new document like this?

**Review by stnguyen90 — CHANGES_REQUESTED** [review]

File: app/controllers/api/teams.php (hunk 6 above)
Comment (ChiragAgg5k) [reply app/controllers/api/teams.php:585]: from my understanding `updateDocument` will overlap these attribute with already existing one in dbForProject, and hence `joined` and `invited` will be updated

And `id` is just there so it doesnt need to be stored in separate variable.

Screenshot 2025-01-17 at 10 36 54 PM

Comment (stnguyen90) [reply app/controllers/api/teams.php:585]: For consistency, let's update the document that exists in memory instead. Like:

https://github.com/appwrite/appwrite/blob/7ecba8c0f282567911904de266ec1f0b4e0546a6/app/controllers/api/users.php#L1232

Remember: 

1. $membership is already the existing document because it was fetched some lines above
2. Joined and confirm should only be updated if the request is from a privileged use or API key
3. What about invited timestamp?

**Review by stnguyen90 — CHANGES_REQUESTED** [review]

File: app/controllers/api/teams.php (hunk 6 above)
Comment (ChiragAgg5k) [reply app/controllers/api/teams.php:585]: Ohhh okay, got it 👍

**Review by stnguyen90 — APPROVED** [review]
