### PR TITLE
fix: validate relationship document ID

### LINKED ISSUE #10612: Can create row with invalid id
### 👟 Reproduction steps

I used `tablesDB.updateRow` to create row in a related table with an invalid value as the `$id`.

Now, I want to delete this row, but I can't because the $id is invalid:

Image

```
"Invalid `rowId` param: UID must contain at most 36 chars. Valid chars are a-z, A-Z, 0-9, and underscore. Can't start with a leading underscore"
```

I also deleted parent table to trigger a cascade deletion, but the row is still not deleted.

### 👍 Expected behavior

- It should not be possible to create a row with an incorrect $id
- It should be possible to delete a row with an incorrect $id

### 👎 Actual Behavior

- It is possible to create a row with an incorrect $id
- It is not be possible to delete a row with an incorrect $id

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

- node-appwrite 18.0.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by premtsd-code**
## What does this PR do?

Validates relationship document IDs using `CustomId` validator to prevent creating documents/rows with invalid IDs.

**Changes:**
- Adds `validateRelationship()` helper method in base `Action.php` class to avoid code duplication
- Validates relationship document `$id` values (max 36 chars, valid characters: a-z, A-Z, 0-9, period, hyphen, underscore, can't start with special char)
- Rejects invalid relationship value types with a clear error message

**Files changed:**
- `src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Action.php`
- `src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Create.php`
- `src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Update.php`
- `src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Upsert.php`
- `tests/e2e/Services/Databases/TablesDB/DatabasesBase.php`

## Test Plan

- Added comprehensive test cases in `tests/e2e/Services/Databases/TablesDB/DatabasesBase.php`
- All existing tests pass (109 tests, 2907 assertions)

## Related PRs and Issues

- Fixes #10612

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

File: src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Action.php [hunk 1]
```diff
@@ -249,6 +251,35 @@ protected function removeReadonlyAttributes(
...
+
+        if ($relationId !== null) {
+            $validator = new CustomId();
+            if (!$validator->isValid($relationId)) {
+                throw new Exception(Exception::GENERAL_BAD_REQUEST, $validator->getDescription());
+            }
+        }
+
+        return [$relationId, $relation];
+    }
```
Comment (premtsd-code) [inline src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Action.php:281]: Seperated assigning UniqueID to caller method

File: src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Action.php [hunk 2]
```diff
@@ -249,6 +250,30 @@ protected function removeReadonlyAttributes(
...
+    /**
+     * Validate relationship values.
+     * Handles Document objects, ID strings, and associative arrays.
+     */
+    protected function validateRelationship(mixed $relation): void
+    {
+        $relationId = null;
+
+        if ($relation instanceof Document) {
+            $relationId = $relation->getAttribute('$id');
```
Comment (ItzNotABug) [inline src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Action.php]: `relation->getId();` its the same underneath.

**Review by ItzNotABug — DISMISSED** [review]

**Review by ArnabChatterjee20k — DISMISSED** [review]

File: src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Action.php [hunk 3]
```diff
@@ -249,6 +250,32 @@ protected function removeReadonlyAttributes(
...
+     */
+    protected function validateRelationship(mixed $relation): void
+    {
+        $relationId = null;
+
+        if ($relation instanceof Document) {
+            $relationId = $relation->getId();
+        } elseif (\is_string($relation)) {
+            $relationId = $relation;
+        } elseif (\is_array($relation) && \array_values($relation) !== $relation) {
```
Comment (abnegate) [inline src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Action.php]: We can use `!\array_is_list()` here instead of the array_values check since we're on PHP 8.3

File: tests/e2e/Services/Databases/TablesDB/DatabasesBase.php [hunk 4]
```diff
@@ -7626,6 +7626,274 @@ public function testUpdateWithExistingRelationships(array $data): void
...
+                'x-appwrite-project' => $this->getProject()['$id'],
+                'x-appwrite-key' => $this->getProject()['apiKey']
+            ]));
+            $columnKeys = array_column($columns['body']['columns'], 'key');
+            if (in_array('children', $columnKeys)) {
+                $childrenFound = true;
+                break;
+            }
+            usleep(200000);
+        }
```
Comment (abnegate) [inline tests/e2e/Services/Databases/TablesDB/DatabasesBase.php]: We have a helper method, `assertEventually` that can handle this kind of polling internally

File: src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Action.php [hunk 5]
```diff
@@ -249,6 +250,32 @@ protected function removeReadonlyAttributes(
...
+            $relationId = $relation['$id'] ?? null;
+        } else {
+            throw new Exception(Exception::GENERAL_BAD_REQUEST, 'Relationship value must be an object, document ID string, or associative array');
+        }
+
+        if ($relationId !== null) {
+            $validator = new CustomId();
+            if (!$validator->isValid($relationId)) {
+                throw new Exception(Exception::GENERAL_BAD_REQUEST, $validator->getDescription());
+            }
```
[the remark this answers is not in the document]
Comment (abnegate) [reply src/Appwrite/Platform/Modules/Databases/Http/Databases/Collections/Documents/Action.php:279]: @premtsd-code Here we can use `RELATIONSHIP_VALUE_INVALID` instead of plain `GENERAL_BAD_REQUEST`

**Review by abnegate — APPROVED** [review]
