### PR TITLE
Fix project deletion

### LINKED ISSUE #6252: 🐛 Bug Report: Unable to Delete the project tables from DB when Project is deleted from Console
### 👟 Reproduction steps

I installed a fresh Appwrite Instance and added a domain and SSL has been generated. 

I have created a new project and added Web integration. 

Then I went to Project Settings and deleted the project. The Project is deleted from the Console. 

I waited two minutes so that I give enough time `appwrite-worker-delete` workers to get executed.

I logged into  `appwrite-mariadb` container  and did `SHOW TABLES` in `appwrite` database and I can see all the tables there. 

Main Error Msg from Log:
================

> Utopia\Database\Exception: Collection "domains" not found in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php:4053

Here is the complete Log from `appwrite-worker-deletes`:

```
[critical] (Job{v1-deletes} | ID: bcad93b55474b31614efd449e4be7281 | DeletesV1 | [{"project":{"$id":"console","$internalId":"console","name":"Appwrite","$collection":"projects","description":"Appwrite core engine","logo":"","teamId":-1,"webhooks":[],"keys":[],"platforms":[{"$collection":"platforms","name":"Localhost","type":"web","hostname":"localhost"},{"$collection":"platforms","name":"Current Host","type":"web","hostname":"awtest.maitretech.com"}],"legalName":"","legalCountry":"","legalState":"","legalCity":"","legalAddress":"","legalTaxId":"","auths":{"invites":true,"limit":1,"duration":31536000},"authWhitelistEmails":[],"authWhitelistIPs":[],"authProviders":{"githubEnabled":true,"githubSecret":"","githubAppid":""}},"type":"document","document":{"teamInternalId":"1","teamId":"650441186bedc466112d","name":"welcome","region":"default","description":"","database":"database_db_main","logo":"","url":"","version":"1.4.2","legalName":"","legalCountry":"","legalState":"","legalCity":"","legalAddress":"","legalTaxId":"","services":[],"smtp":[],"templates":[],"auths":{"limit":0,"maxSessions":10,"passwordHistory":0,"passwordDictionary":false,"duration":31536000,"personalDataCheck":false,"emailPassword":true,"usersAuthMagicURL":true,"anonymous":true,"invites":true,"JWT":true,"phone":true},"authProviders":[],"platforms":[{"projectInternalId":"2","projectId":"welcome","type":"web","name":"web","key":"","store":"","hostname":"*","$id":"65044237d198833f166d","$internalId":"2","$createdAt":"2023-09-15T11:38:31.858+00:00","$updatedAt":"2023-09-15T11:38:38.616+00:00","$permissions":["read(\"any\")","update(\"any\")","delete(\"any\")"],"$collection":"platforms"}],"webhooks":[],"keys":[],"search":"welcome welcome","$internalId":"2","$id":"welcome","$createdAt":"2023-09-15T11:38:21.481+00:00","$updatedAt":"2023-09-15T11:38:21.481+00:00","$permissions":["read(\"team:650441186bedc466112d\")","update(\"team:650441186bedc466112d\/owner\")","update(\"team:650441186bedc466112d\/developer\")","delete(\"team:650441186bedc466112d\/owner\")","delete(\"team:650441186bedc466112d\/developer\")"],"$collection":"projects"},"resource":null,"datetime":null,"hourlyUsageRetentionDatetime":null}]) has failed Utopia\Database\Exception: Collection "domains" not found in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php:4053
Stack trace:
#0 /usr/src/code/app/workers/deletes.php(373): Utopia\Database\Database->find(Object(Utopia\Database\Document), Array)
#1 /usr/src/code/app/workers/deletes.php(50): DeletesV1->deleteProject(Object(Utopia\Database\Document))
#2 /usr/src/code/src/Appwrite/Resque/Worker.php(125): DeletesV1->run()
#3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform()
#4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
#5 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
#6 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
#7 {main}
```

### 👍 Expected behavior

`appwrite-worker-deletes` should delete all the tables from the database 

### 👎 Actual Behavior

Project Tables are not deleted from the backend database and delete worked throws an error mentioned in **Reproduction Steps** Section. 

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite  Versions: 1.4.1 and 1.4.2 (Checked on both Versions after clearing volumes properly)
Remote Server OS: Linux
Used From: Web Console
Host OS: Windows 10 where the web console is opened. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by stnguyen90**
## What does this PR do?

The project deletion failed because old code for deleting domain was still present. By removing the old code and replacing it with the new delete rule code, the project deletion is now working.

Fixes #6252 

## Test Plan

Manually created a project with a project rule and function rule and tested deleting the project. The logs show the process was completed successfully:

Screen Shot 2023-09-15 at 5 03 40 PM

In addition, before and after SQL queries show the records have been removed from the database.

Screen Shot 2023-09-15 at 5 03 53 PM

## Related PRs and Issues

- #6252 

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

**Review by Meldiron — APPROVED** [review]

**Review by TorstenDittmann — APPROVED** [review]

File: app/workers/deletes.php [hunk 1]
```diff
@@ -369,14 +369,6 @@ protected function deleteProject(Document $document): void
         // Delete project certificates
```
Comment (christyjacob4) [inline app/workers/deletes.php:369]: can. you remove this comment now that we don't do this line this line anymore

**Review by christyjacob4 — APPROVED** [review]
Looks good. Please address the comment

Lets also change the base branch to 1.4.x

File: app/workers/deletes.php (hunk 1 above)
Comment (stnguyen90) [reply app/workers/deletes.php]: done

**Review by TorstenDittmann — APPROVED** [review]
