### PR TITLE
Delete linked VCS repos and comments

### LINKED ISSUE #7018: 🐛 Bug Report: Related VCS documents aren't deleted when a function is deleted
### 👟 Reproduction steps

1. Create a project
2. Connect to GitHub
3. Deploy a function using GitHub integration
4. Create a PR on the function repo to create VCS comments
5. Delete the function

### 👍 Expected behavior

All related documents such as:

- installations
- repositories
- vcsComments

### 👎 Actual Behavior

These may not be deleted

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by vermakhushboo**
## What does this PR do?

Deletes documents from VCS repositories and vcsComments collections when a project or a linked function is deleted. 

Fixes #7018, #7019

## Test Plan

Tested manually

## Related PRs and Issues

* https://github.com/appwrite/appwrite/issues/7018
* https://github.com/appwrite/appwrite/issues/7019

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [ ] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

File: src/Appwrite/Platform/Workers/Deletes.php [hunk 1]
```diff
@@ -450,6 +450,23 @@ private function deleteProject(Database $dbForConsole, callable $getProjectDB, c
             Query::equal('projectInternalId', [$projectInternalId])
         ], $dbForConsole);
 
+        // Delete VCS Installations, Repositories and Comments
+        $this->deleteByGroup('installations', [
+            Query::equal('projectInternalId', [$projectInternalId])
+        ], $dbForConsole, function (Document $document) use ($dbForConsole) {
```
Comment (christyjacob4) [inline src/Appwrite/Platform/Workers/Deletes.php:456]: this will delete all the installations of that project ID also... not sure that is expected.

File: src/Appwrite/Platform/Workers/Deletes.php [hunk 2]
```diff
@@ -450,6 +450,23 @@ private function deleteProject(Database $dbForConsole, callable $getProjectDB, c
...
+            $projectInternalId = $document->getAttribute('projectInternalId', '');
```
Comment (christyjacob4) [inline src/Appwrite/Platform/Workers/Deletes.php:457]: why is this in a nested loop ? 

You can keep deletion from the `repositories` table a separate loop.. you only need the `projectInternalID` to identify the repositories

Comment (vermakhushboo) [reply src/Appwrite/Platform/Workers/Deletes.php]: Fixed

File: src/Appwrite/Platform/Workers/Deletes.php [hunk 3]
```diff
@@ -450,6 +450,23 @@ private function deleteProject(Database $dbForConsole, callable $getProjectDB, c
...
         ], $dbForConsole);
 
+        // Delete VCS Installations
+        $this->deleteByGroup('installations', [
+            Query::equal('projectInternalId', [$projectInternalId])
+        ], $dbForConsole);
+
+        // Delete VCS Repositories and Comments
+        $this->deleteByGroup('repositories', [
+            Query::equal('installationInternalId', [$projectInternalId]),
```
Comment (christyjacob4) [inline src/Appwrite/Platform/Workers/Deletes.php:460]: this should not be `installationInternalId` it should be the `projectInternalId`

File: src/Appwrite/Platform/Workers/Deletes.php [hunk 4]
```diff
@@ -450,6 +450,23 @@ private function deleteProject(Database $dbForConsole, callable $getProjectDB, c
...
+        ], $dbForConsole, function (Document $document) use ($dbForConsole) {
+            $providerRepositoryId = $document->getAttribute('providerRepositoryId', '');
+            $projectId = $document->getAttribute('projectId', '');
+            $this->deleteByGroup('vcsComments', [
```
Comment (christyjacob4) [inline src/Appwrite/Platform/Workers/Deletes.php:464]: https://github.com/appwrite/appwrite/blob/main/app/config/collections.php#L4507
VCS comments also has projectInternalId

File: src/Appwrite/Platform/Workers/Deletes.php [hunk 5]
```diff
@@ -450,6 +450,23 @@ private function deleteProject(Database $dbForConsole, callable $getProjectDB, c
...
+        // Delete VCS Repositories and Comments
+        $this->deleteByGroup('repositories', [
+            Query::equal('projectInternalId', [$projectInternalId]),
+        ], $dbForConsole, function (Document $document) use ($dbForConsole) {
+            $providerRepositoryId = $document->getAttribute('providerRepositoryId', '');
+            $projectInternalId = $document->getAttribute('projectInternalId', '');
+            $this->deleteByGroup('vcsComments', [
+                Query::equal('providerRepositoryId', [$providerRepositoryId]),
+                Query::equal('projectInternalId', [$projectInternalId]),
+            ], $dbForConsole);
```
[the remark this answers is not in the document]
Comment (christyjacob4) [reply src/Appwrite/Platform/Workers/Deletes.php]: Fixed 👍

**Review by eldadfux — APPROVED** [review]
