### PR TITLE
fix: Throw error when file token expiry is in the past

### LINKED ISSUE #10323: 🐛 Bug Report: Error creating expired file token
### 👟 Reproduction steps

1. Create a file token with an expiration in the past

### 👍 Expected behavior

1. The Console should not allow it
2. The API call should return an error saying the date is invalid

### 👎 Actual Behavior

The Console allows it:

Image

and then there's a server error:

Image

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by hmacr**
Task: https://linear.app/appwrite/issue/SER-279/error-creating-expired-file-token
Closes #10323

### CODE REVIEW

File: src/Appwrite/Platform/Modules/Tokens/Http/Tokens/Buckets/Files/Create.php [hunk 1]
```diff
@@ -70,6 +70,13 @@ public function __construct()
 
     public function action(string $bucketId, string $fileId, ?string $expire, Response $response, Database $dbForProject, Event $queueForEvents): void
     {
+        if (!is_null($expire)) {
+            $validator = new DatetimeValidator(requireDateInFuture: true, precision: DateTimeValidator::PRECISION_DAYS, offset: 0);
```
Comment (Meldiron) [inline src/Appwrite/Platform/Modules/Tokens/Http/Tokens/Buckets/Files/Create.php]: This is not in param directly, to allow us to change exception message.
But can we make validaiton description nicer, so we dont need this?

There are more endpoitns that would benefit from nicer error message.

**Review by Meldiron — APPROVED** [review]
