### PR TITLE
Fix 'Missing required attribute "expire"' on `users.createSession()`

### LINKED ISSUE #8280: 🐛 Bug Report: Invalid document structure: Missing required attribute "expire" on `users.createSession()`
### 👟 Reproduction steps

This bug happens when I try to use `createSession(userId)` from the Node SDK, but it appears to also be happening in the PHP SDK when using `$users->createSession($userId)`.

### 👍 Expected behavior

A session should be created for the user ID that is provided.

### 👎 Actual Behavior

The following errors gets thrown and logged
```
[Error] Timestamp: 2024-06-14T12:44:49+00:00
[Error] Method: POST
[Error] URL: /v1/users/:userId/sessions
[Error] Type: Utopia\Database\Exception\Structure
[Error] Message: Invalid document structure: Missing required attribute "expire"
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
[Error] Line: 3070
```

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I have tried this on both Appwrite 1.5.4 and 1.5.7, both running on a DigitalOcean droplet. I'm using the latest version of the Node SDK

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by stnguyen90**
### Fix expire error when creating user session 

Before this, the Create session API call would throw:

> Invalid document structure: Missing required attribute "expire"

This is because the `expire` attribute is required, but it was omitted
from the document. This PR ensures the `expire` attribute is set when
creating the session document.

Fixes #8280 

### Update session secret to be longer

The create session endpoint created a 6 character secret which is too
short. This changes the secret to be 256 characters which is in line
with the secret for `account.createEmailPasswordSession()`.

## Test Plan

Added a test case

## Related PRs and Issues

- #8280 

Parent PR:

* https://github.com/appwrite/appwrite/pull/8317

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

File: app/controllers/api/users.php [hunk 1]
```diff
@@ -1784,7 +1784,7 @@ function createUser(string $hash, mixed $hashOptions, string $userId, ?string $e
             throw new Exception(Exception::USER_NOT_FOUND);
         }
 
-        $secret = Auth::codeGenerator();
+        $secret = Auth::tokenGenerator(Auth::TOKEN_LENGTH_SESSION);
```
Comment (stnguyen90) [inline app/controllers/api/users.php:1787]: @loks0n, do you remember why the secret was created using `Auth::codeGenerator();` which creates a 6 character code?

**Review by abnegate — APPROVED** [review]
