### PR TITLE
Fix function timeout

### LINKED ISSUE #6234: 🐛 Bug Report: Function fails before timeout
### 👟 Reproduction steps

1. Create a function that takes 120 seconds to complete and has a timeout of 240 seconds
2. Execute the function

### 👍 Expected behavior

The function executes successfully.

### 👎 Actual Behavior

The function fails after about 1 minute with:

```
An internal curl error has occurred within the executor! Error Msg: Connection reset by peer\nError Code: 500
```

image

`openruntimes-executor` logs shows:

```
openruntimes-executor  | 2023-09-13T21:50:57.710159636Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:50:57.712701536Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:51:57.709376166Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:51:57.710428756Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:52:57.708922472Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:52:57.710464182Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:53:57.710213540Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:53:57.711186120Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:54:57.708778609Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:54:57.709870409Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:55:50.853424759Z Skipping runtimes stats loop due to error: Docker Error: EOF
openruntimes-executor  | 2023-09-13T21:55:50.853927049Z 
openruntimes-executor  | 2023-09-13T21:55:57.709138899Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:55:57.711327889Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:55:57.768026941Z [Error] Type: Exception
openruntimes-executor  | 2023-09-13T21:55:57.768076261Z [Error] Message: An internal curl error has occurred within the executor! Error Msg: Connection reset by peer
openruntimes-executor  | 2023-09-13T21:55:57.768218691Z [Error] File: /usr/local/app/http.php
openruntimes-executor  | 2023-09-13T21:55:57.768254591Z [Error] Line: 1021
openruntimes-executor  | 2023-09-13T21:55:58.041696876Z Successfully removed test-65022f347071fb788afa
openruntimes-executor  | 2023-09-13T21:56:57.709221683Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:56:57.712822882Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:57:57.709210892Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:57:57.710165702Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:58:57.708959414Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:58:57.710204513Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:59:57.709086915Z Running maintenance task ...
```

Looking at the logs, it seems like the maintenance task is running way too often. It seems this value should be 1 hour instead of 60 seconds:

https://github.com/appwrite/appwrite/blob/5717fbe28243a7616434d908554db51d28c4f35d/app/config/variables.php#L847C7-L855

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Tested on 1.4.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by stnguyen90**
## What does this PR do?

    Fix the _APP_FUNCTIONS_MAINTENANCE_INTERVAL variable
    
    * Clarify the description and make it match the other maintenance
      variables.
    * Fix the introduction since it was introduced in 1.4.0 and not 1.2.0.
    * Fix the default value because it was 1 hour in the previous versions
      and a number that is too low will conflict with a function's timeout.

Fixes #6234 

## Test Plan

Manually tested.

## Related PRs and Issues

- #6234 

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

File: app/config/variables.php [hunk 1]
```diff
@@ -846,10 +846,11 @@
             ],
             [
                 'name' => '_APP_FUNCTIONS_MAINTENANCE_INTERVAL',
-                'description' => 'Interval how often executor checks for inactive runimes. The default value is 60 seconds.',
-                'introduction' => '1.2.0',
```
Comment (christyjacob4) [inline app/config/variables.php:850]: The introduction should be `1.2.0` itself

Comment (stnguyen90) [reply app/config/variables.php:850]: I'm pretty sure it was introduced in [1.4.0](https://github.com/appwrite/appwrite/blob/e82c22ac1eca532fd83129d39a134a6b2ccf898e/app/config/variables.php#L847). You won't find it in [1.3.8](https://github.com/appwrite/appwrite/blob/1.3.8/app/config/variables.php).

Comment (christyjacob4) [reply app/config/variables.php:850]: Alright thanks for confirming 👍

**Review by christyjacob4 — APPROVED** [review]
