### PR TITLE
Fix users create session secret

### LINKED ISSUE #8569: 🐛 Bug Report: "Users.createSession()" returns invalid session secret
### 👟 Reproduction steps

1. Create a session via "Users.createSession()"
2. Set the session secret in "Client.setSession()"
3. Call "Accounts.get()"

### 👍 Expected behavior

No error.
Get a valid user object response back.

### 👎 Actual Behavior

**Error => "User (role: guests) missing scope (account)"**

Session secret when creating one  via "Users.createSession()"
image

Session secret when creating one via "Account.createEmailPasswordSession()"
image

The one from "Users.createSession()" is not properly encoded and therefore not returned as JWT.

Users.createSession()
https://github.com/appwrite/appwrite/blob/9301bddd8b161e6f4207e4b86d9908cacbdf9ef0/app/controllers/api/users.php#L1815

Account.createEmailPasswordSession()
https://github.com/appwrite/appwrite/blob/9301bddd8b161e6f4207e4b86d9908cacbdf9ef0/app/controllers/api/account.php#L808

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by stnguyen90**
## What does this PR do?

1. Include at least 1 factor because the minumum number of factors
   required when mfa is disabled is 1.
2. Purge the cached user document to ensure the new session is included
   in subsequent requests for the user.
3. Fix the encoding of the secret to match other parts of the codebase.

Fixes #8569 

## Test Plan

Updated test case

## Related PRs and Issues

- #8569

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

**Review by loks0n — APPROVED** [review]

File: app/controllers/api/users.php [hunk 1]
```diff
@@ -1816,8 +1817,11 @@ function createUser(string $hash, mixed $hashOptions, string $userId, ?string $e
         $countryName = $locale->getText('countries.' . strtolower($session->getAttribute('countryCode')), $locale->getText('locale.country.unknown'));
 
         $session = $dbForProject->createDocument('sessions', $session);
+
+        $dbForProject->purgeCachedDocument('users', $user->getId());
+
         $session
-            ->setAttribute('secret', $secret)
```
Comment (loks0n) [inline app/controllers/api/users.php:1820]: We have to document this right, it's sort of breaking? Some people could be relying on it

Comment (stnguyen90) [reply app/controllers/api/users.php:1820]: I don't think anyone is using it because it doesn't work.
