### PR TITLE
Fix deploy from git with space

### LINKED ISSUE #8506: 🐛 Bug Report: Cannot deploy from GitHub if folder has space
### 👟 Reproduction steps

1. Create a function in a folder like `functions/with a space` like:

image

2. Create a function in Appwrite, setting Root directory to the folder (e.g. `functions/with a space`)

### 👍 Expected behavior

The function builds successfully

### 👎 Actual Behavior

Build fails with error:

```
Docker Error: Preparing for build ...
cp: cannot stat '/mnt/code/*': No such file or directory

/usr/src/code/vendor/appwrite/server-ce/src/Executor/Executor.php:97
#0 /usr/src/code/vendor/appwrite/server-ce/src/Appwrite/Platform/Workers/Builds.php(410): Executor\Executor->createRuntime('66b641d4154e261...', 'delete', '/storage/functi...', 'openruntimes/da...', 'v3', true, 'lib/main.dart', '/storage/builds...', Array, 'tar -zxf /tmp/c...')
#1 [internal function]: Appwrite\Platform\Workers\Builds->Appwrite\Platform\Workers\{closure}()
#2 {main}
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by byawitz**
## What does this PR do?

Closes #8506

## Test Plan
Tested manually with two git repositories one with space and one without

## Related PRs and Issues
- #8506 

## Checklist

- [] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

File: src/Appwrite/Platform/Workers/Builds.php [hunk 1]
```diff
@@ -238,6 +239,20 @@ protected function buildDeployment(Device $deviceForFunctions, Func $queueForFun
                     throw new \Exception('Unable to clone code repository: ' . $stderr);
                 }
 
+                // Local refactoring for function folder with spaces
+                if (str_contains($rootDirectory, ' ')) {
+                    $rootDirectoryWithoutSpaces = str_replace(' ', '', $rootDirectory);
+                    $from = $tmpDirectory . '/' . $rootDirectory;
+                    $to = $tmpDirectory . '/' . $rootDirectoryWithoutSpaces;
+                    $exit = Console::execute('mv "' . $from . '" "' . $to . '"', '', $stdout, $stderr);
```
Comment (christyjacob4) [inline src/Appwrite/Platform/Workers/Builds.php:247]: we should probably use `escapeshellarg` to clean up the commands before we run them

**Review by christyjacob4 — APPROVED** [review]
