### PR TITLE
fix: Allow Adding User Over Limit From Console In Team Membership

### LINKED ISSUE #5516: 🐛 Bug Report: with Users limited to 1, creating team membership in console gives restricted error
### 👟 Reproduction steps

1. Auth -> Security, set Users limit to 1.
2. Auth -> Teams, Create a new team
3. Select the new team and select Members tab
4. Press the create membership button
5. Add a new unregistered user email address with any roles/name

### 👍 Expected behavior

It should create the new user for that email address if it doesn't exist (ideally with a confirmation?) even though the user limit is exceeded since it is being created through the console or via an API key.

### 👎 Actual Behavior

It returns an error message "Project registration is restricted. Contact your administrator for more information."
It works as expected if the user/email already exists.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I am using 1.3.4 through the console on a self hosted localhost linux development environment with _APP_ENV=development

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by ketanbaitule**
## What does this PR do?

It allows Adding user over limit from console in team membership.

Fixes #5516 

## Test Plan

Manual

https://github.com/appwrite/appwrite/assets/111437670/bd9c3c5b-05f4-4c0c-ab72-7752da39b050

## Related PRs and Issues

- #5516 

## Checklist

- [x] Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- [x] If the PR includes a change to an API's metadata (desc, label, params, etc.), does it also include updated API specs and example docs?

### CODE REVIEW

File: app/controllers/api/teams.php [hunk 1]
```diff
@@ -453,7 +453,7 @@
         if (empty($invitee)) { // Create new user if no user with same email found
             $limit = $project->getAttribute('auths', [])['limit'] ?? 0;
 
-            if ($limit !== 0 && $project->getId() !== 'console') { // check users limit, console invites are allways allowed.
+            if (!$isPrivilegedUser && $limit !== 0 && $project->getId() !== 'console') { // check users limit, console invites are allways allowed.
```
Comment (stnguyen90) [inline app/controllers/api/teams.php:456]: This is great! Let's also add `!$isAppUser` too so that it's still possible to create a user with an API key.

```suggestion
            if (!$isPrivilegedUser && !$isAppUser && $limit !== 0 && $project->getId() !== 'console') { // check users limit, console invites are allways allowed.
```

**Review by stnguyen90 — CHANGES_REQUESTED** [review]

File: app/controllers/api/teams.php (hunk 1 above)
Comment (ketanbaitule) [reply app/controllers/api/teams.php]: I accidently clicked on commmit

Comment (ketanbaitule) [reply app/controllers/api/teams.php]: No, We cannot add, If its AppUser, he should not be able to add more user if count increases

Comment (ketanbaitule) [reply app/controllers/api/teams.php]:
```
if (!$isPrivilegedUser && $limit !== 0 && $project->getId() !== 'console') { // check users limit, console invites are allways allowed.
                $total = $dbForProject->count('users', [], APP_LIMIT_USERS);

                if ($total >= $limit) {
                    throw new Exception(Exception::USER_COUNT_EXCEEDED, 'Project registration is restricted. Contact your administrator for more information.');
                }
 }
```

The if condition checks if its privileged, it would not check the limit but if it is app user it should check it

Comment (stnguyen90) [reply app/controllers/api/teams.php:456]: app user means API key. API key should not be restricted by this.

**Review by stnguyen90 — CHANGES_REQUESTED** [review]

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
Would you please also add test cases. The best place is probably here:

https://github.com/appwrite/appwrite/blob/0a3914df93cb5e5efdf69603edb77eadeb9eca41/tests/e2e/Services/Projects/ProjectsConsoleClientTest.php#L1243-L1254

2 API calls should be called using the Console account (include the headers like [here](https://github.com/appwrite/appwrite/blob/0a3914df93cb5e5efdf69603edb77eadeb9eca41/tests/e2e/Services/Projects/ProjectsConsoleClientTest.php#L1216)):

1. POST /users
2. POST /teams/id/memberships (you'll need to create the team first too)

**Review by stnguyen90 — APPROVED** [review]
