### PR TITLE
fix-723-Doctor CLI: `_APP_OPTIONS_FORCE_HTTPS=disabled` not correctly evaluated

### LINKED ISSUE #723: Doctor CLI: `_APP_OPTIONS_FORCE_HTTPS=disabled` not correctly evaluated
## 🐛 Bug Report

Doctor CLI shows `🟢 HTTP force option is enabled`, although it is disabled.

## Have you spent some time to check if this issue has been raised before?

I searched the issues for "doctor" and didn't find a similar bug. Also discussed on Discord.

## To Reproduce

1. Set [`environment` variable](https://appwrite.io/docs/environment-variables) in `docker-compose.yml` to `disabled`:
   ` - _APP_OPTIONS_FORCE_HTTPS=disabled`
2. Apply configuration with `docker-compose up -d`
3. Run doctor `docker-compose exec appwrite doctor`

## Expected behavior

Show this: 
🔴 HTTP force option is disabled

## Actual Behavior

Screenshot from 2020-11-01 21-45-12_2

Shown:
🟢 HTTP force option is enabled

## Your Environment

- Appwrite Dev branch 0.7.x db7d7dd89ed7d82d45f0f3a14990de02291abfd1
- Ubuntu Server 20.04 arm64

## Solution

Check for string `enabled` instead of `empty`, see [doctor.php](https://github.com/appwrite/appwrite/blob/564c1f03814528cdbb7bdd584ca8309b7ea5e5a4/app/tasks/doctor.php#L78)

```
if (App::getEnv('_APP_OPTIONS_FORCE_HTTPS', 'disabled') === 'enabled')
```

If you confirm, I'd happy to start a Merge-Request :smile:

### PR DESCRIPTION
**Pull request by eldadfux**
Fixes #723

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

Using existing tests.

## Related PRs and Issues

#723 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

File: app/tasks/doctor.php [hunk 1]
```diff
@@ -25,36 +25,36 @@
...
-            Console::log('🔴 CNAME target has a public suffix');
+            Console::log('🔴 CNAME target has a public suffix ('.$domain->get().')');
         }
         else {
-            Console::log('🟢 CNAME target has a public suffix');
+            Console::log('🟢 CNAME target has a public suffix ('.$domain->get().')');
         }
         
-        if(App::getEnv('_APP_OPENSSL_KEY_V1', 'your-secret-key') === 'your-secret-key') {
+        if(App::getEnv('_APP_OPENSSL_KEY_V1', 'your-secret-key') === 'your-secret-key' || empty(App::getEnv('_APP_OPENSSL_KEY_V1', 'your-secret-key'))) {
```
Comment (Gustl22) [inline app/tasks/doctor.php:43]: @eldadfux I think the second part is useless, as 'your-secret-key' is used as default, if environment variable is empty. (`empty == "" == null == 0 == []`)

File: app/tasks/doctor.php [hunk 2]
```diff
@@ -25,36 +25,36 @@
...
-        if(App::getEnv('_APP_ENV', 'development') === 'development') {
+        if(App::getEnv('_APP_ENV', 'development') !== 'production') {
             Console::log('🔴 App enviornment is set for production');
         }
         else {
             Console::log('🟢 App enviornment is set for production');
         }
 
-        if(App::getEnv('_APP_OPTIONS_ABUSE', 'disabled') === 'disabled') {
+        if(App::getEnv('_APP_OPTIONS_ABUSE', 'disabled') === 'disabled' || empty(App::getEnv('_APP_OPTIONS_ABUSE', 'disabled'))) {
```
Comment (Gustl22) [inline app/tasks/doctor.php:57]: Same here :)

File: app/tasks/doctor.php [hunk 3]
```diff
@@ -75,11 +75,11 @@
             Console::log('🟢 Console access limits are enabled');
         }
         
-        if(empty(App::getEnv('_APP_OPTIONS_FORCE_HTTPS', null))) {
-            Console::log('🔴 HTTP force option is disabled');
+        if('disabled' === App::getEnv('_APP_OPTIONS_FORCE_HTTPS', 'disabled') || empty(App::getEnv('_APP_OPTIONS_FORCE_HTTPS', 'disabled'))) {
```
Comment (Gustl22) [inline app/tasks/doctor.php:78]: More robust would be `'enabled' !== App::getEnv('_APP_OPTIONS_FORCE_HTTPS', 'disabled')` and the second part not needed.
Compared to here: https://github.com/appwrite/appwrite/blob/265fd53659e3ecde54c963e79b649f521745c176/app/controllers/general.php#L103

**Review by Gustl22 — COMMENTED** [review]
I think there are some redundant checks :)

File: app/tasks/doctor.php (hunk 1 above)
Comment (eldadfux) [reply app/tasks/doctor.php:43]: Maybe we should change the message description, because using an empty key is not way better than using the default one.

File: app/tasks/doctor.php (hunk 2 above)
Comment (eldadfux) [reply app/tasks/doctor.php:57]: The Appwrite source code has an internal default value so empty string would also be considered as disabled. I'll change the condition to `'enabled' !== ...`

File: app/tasks/doctor.php (hunk 3 above)
Comment (eldadfux) [reply app/tasks/doctor.php:78]: 100%

File: app/tasks/doctor.php (hunk 1 above)
Comment (Gustl22) [reply app/tasks/doctor.php:43]: I think you can't enter an empty key, as if so, it would be replaced by default variable in the second param of `App::getEnv`.

Comment (Gustl22) [reply app/tasks/doctor.php:43]: Or you meant the second part to be `empty(App::getEnv('_APP_OPENSSL_KEY_V1'))` only, and change the text accordingly, or even make it its own case to explicitely stating that key is empty.

Comment (eldadfux) [reply app/tasks/doctor.php:43]: Yes, that was my mistake, I'll fix it :)

**Comment by eldadfux** [comment]
@Gustl22 care to review the new PR?

https://github.com/appwrite/appwrite/pull/727
